language: php
php:
  - 7.0
  - 7.1
services:
  - mysql
sudo: false
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
