language: php
php:
  - 7.3
  - 7.4
  - 8.0
services:
  - mysql
sudo: false
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
