language: php
php:
  - 7.2
  - 7.3
  - 7.4
services:
  - mysql
sudo: false
before_install:
  - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
