language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
services:
  - mysql
sudo: false
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
before_script:
  - if [ $DB = 'mysql' ]; then mysql -e 'create database psx;'; fi;
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
